## how to run
## and get into interactive shell
#
# docker-compose up
# docker-compose run --rm magick
#

  magick:
    image: jess/imagemagick
    container_name: jess-magick
    hostname: jessmagick

    #user: "${UID}:${GID}"
    user: "1000:1000"

    #stdin_open: true
    #tty: true

    # ports:
    #   - 3080:80
    #   - 3443:443

    volumes:
      - ${HOME}:${HOME}
      - /ssd:/ssd
      - /bs2:/bs2
      - /sg8:/sg8

    # It will go into bash, for this container, it may be
    # __magick__, so I override it.
    entrypoint: bash
    #command: /bin/bash

    working_dir: ${HOME}
    environment:
      - USER=magick

