  rejson:
    image: redislabs/rejson:latest
    container_name: redis-redisjson
    hostname: redis

    ports:
      - 6379:6379

    volumes:
      - ${HOME}/usedocker/rejson/conf:/conf
      - ${HOME}/usedocker/rejson/data:/data
    # working_dir: ${HOME}

    #command: bash
    restart: always

## how to run
#
# docker-compose up -d ; sleep 1 ;
# docker-compose run --rm rejson
#
## and get into interactive shell
#
# https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e
#
# docker-entrypoint.sh
#
