  ubut:
    image: ubuntu:18.04
    container_name: ubuntu-test
    hostname: ubuntu

    #user: "${UID}:${GID}"
    user: "1000:1000"
    
    #stdin_open: true
    #tty: true

    # ports:
    #   - 3080:80
    #   - 3443:443

    volumes:
      - /home/rasmus:/home/rasmus
    working_dir: /home/rasmus

    command: /bin/bash
    #restart: always

## how to run
#
# docker-compose up ; sleep 1 ;
# docker-compose run --rm ubut
#
## and get into interactive shell
#
# https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e
#
