  myapp:
    image: jrottenberg/ffmpeg
    container_name: ffmpeg-test
    hostname: ffmpeg

    #user: "${UID}:${GID}"
    user: "1000:1000"
    
    #stdin_open: true
    #tty: true

    # mount the most disk partition
    volumes:
      - ${HOME}:${HOME}
      - /ssd:/ssd
      - /bs2:/bs2
      - /sg8:/sg8
    working_dir: /sg8/Videos

    # override it and use bash to work
    entrypoint: bash
    #command: bash
    #restart: always

## how to run
#
# docker-compose up ; sleep 1 ;
# docker-compose run --rm myapp
#
## and get into interactive shell
#
# https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e
#
